In [1]:
#playing with NumPy

import numpy as np

n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [2]:
n2 = np.zeros((4,4))
n2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
n3 = np.full((2,2),45)
n3

array([[45, 45],
       [45, 45]])

In [4]:
n4 = np.arange(10,20)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
n5 = np.arange(10,50,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
import random

In [14]:
n6 = np.random.randint(1,100,5)
n6

array([26, 77, 37, 71, 34])

In [17]:
n6.shape


(5,)

In [18]:
n7 = np.array([[1,2,3],[4,5,6]])
n7

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n7.shape

(2, 3)

In [20]:
n7.shape = (3,2)
n7

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
n8 = np.array([1,2,3,5,6])
n9 = np.array([12,2,23,34,45])
n10 = np.vstack((n8,n9)) # vertical stacking
n10

array([[ 1,  2,  3,  5,  6],
       [12,  2, 23, 34, 45]])

In [22]:
n11 = np.hstack((n8,n9)) #horizontal stacking
n11

array([ 1,  2,  3,  5,  6, 12, 23, 23, 34, 45])

In [23]:
n12 = np.column_stack((n8,n9)) # column wise stacking
n12

array([[ 1, 12],
       [ 2, 23],
       [ 3, 23],
       [ 5, 34],
       [ 6, 45]])

In [25]:
for i in n12:
    print(i)

[ 1 12]
[ 2 23]
[ 3 23]
[ 5 34]
[ 6 45]


In [31]:
np.intersect1d(n8,n9) #it gives common element from both elements

array([2])

In [30]:
np.setdiff1d(n8,n9) #it will return the elements which are only present in first array by compairing with the other given array

array([1, 3, 5, 6])

In [32]:
np.setdiff1d(n9,n8)

array([12, 23, 34, 45])

In [34]:
n13 = n8 + n9
n13

array([13,  4, 26, 39, 51])

In [36]:
n14 = n8 - n9
n14

array([-11,   0, -20, -29, -39])

In [38]:
n15 = n8 * n9
n15

array([ 12,   4,  69, 170, 270])

In [40]:
n16 = n9 / n8
n16

array([12.        ,  1.        ,  7.66666667,  6.8       ,  7.5       ])

In [43]:
np.sum([n8,n9],axis = 0)  #addition along column

array([13,  4, 26, 39, 51])

In [44]:
np.sum([n8,n9],axis = 1)  #addition along row

array([ 17, 116])

In [47]:
nn = np.array([1,2,3,4])
nn
#addition
nn = nn + 2
nn

array([3, 4, 5, 6])

In [48]:
#substraction
nn = nn - 2
nn

array([1, 2, 3, 4])

In [49]:
#multiplication
nn = nn * 2
nn

array([2, 4, 6, 8])

In [51]:
#Divide
nn = nn / 2
nn

array([0.5, 1. , 1.5, 2. ])

In [52]:
#mean 

np.mean(nn)

1.25

In [53]:
#median 
np.median(nn)

1.25

In [55]:
#standard deviation
np.std(nn)

0.5590169943749475

In [56]:
#numpy matrix

na = np.array([[1,2,3],[4,5,6],[7,8,9]])
na

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
na[-1:]

array([[7, 8, 9]])

In [58]:
na[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [62]:
na[:,1]

array([2, 5, 8])

In [63]:
#numpy transpose
na.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
ba = np.array([[11,21,31],[41,51,61],[71,81,91]])
ba

array([[11, 21, 31],
       [41, 51, 61],
       [71, 81, 91]])

In [65]:
#matrix multiplication
na.dot(ba)

array([[ 306,  366,  426],
       [ 675,  825,  975],
       [1044, 1284, 1524]])

In [66]:
na.dot(na)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [67]:
ba.dot(na)

array([[ 312,  375,  438],
       [ 672,  825,  978],
       [1032, 1275, 1518]])

In [68]:
#save and load 
ns = np.array([1,2,3])
np.save("new",ns)

In [69]:
nd = np.load("new.npy")
nd

array([1, 2, 3])